package CricketManagementSystem;

import java.awt.Toolkit;
import javax.swing.JOptionPane;

/**
 *
 * @author amarj
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
	initComponents();
	setIcon();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        newPlayer = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        showPlayers = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        addUpdateDelete = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        showTeamDetails = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        udpateDeleteMatch = new javax.swing.JMenuItem();
        jSeparator9 = new javax.swing.JPopupMenu.Separator();
        showMatches = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        udpateDeleteScore = new javax.swing.JMenuItem();
        jSeparator12 = new javax.swing.JPopupMenu.Separator();
        showScores = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        updateDeleteStadium = new javax.swing.JMenuItem();
        jSeparator15 = new javax.swing.JPopupMenu.Separator();
        showStadiums = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        Logout = new javax.swing.JMenuItem();
        jSeparator16 = new javax.swing.JPopupMenu.Separator();
        exitApplication = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        AboutUs = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cricket Management System [Dashboard]");
        setBackground(new java.awt.Color(0, 102, 102));
        setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        setName("home"); // NOI18N
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/home_page_background.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1930, 940));

        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 180, -1, -1));

        jMenuBar1.setBackground(new java.awt.Color(51, 51, 51));
        jMenuBar1.setForeground(new java.awt.Color(0, 102, 102));

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/player.png"))); // NOI18N
        jMenu1.setText("Player");
        jMenu1.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N

        newPlayer.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        newPlayer.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        newPlayer.setText("Add/Update/Delete Player");
        newPlayer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newPlayerActionPerformed(evt);
            }
        });
        jMenu1.add(newPlayer);
        jMenu1.add(jSeparator1);

        showPlayers.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        showPlayers.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        showPlayers.setText("All Player Details");
        showPlayers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showPlayersActionPerformed(evt);
            }
        });
        jMenu1.add(showPlayers);

        jMenuBar1.add(jMenu1);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/team.png"))); // NOI18N
        jMenu2.setText("Team");
        jMenu2.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N

        addUpdateDelete.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        addUpdateDelete.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        addUpdateDelete.setText("Add/Update/Delete Team");
        addUpdateDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addUpdateDeleteActionPerformed(evt);
            }
        });
        jMenu2.add(addUpdateDelete);
        jMenu2.add(jSeparator4);

        showTeamDetails.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        showTeamDetails.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        showTeamDetails.setText("Show All Teams Details");
        showTeamDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showTeamDetailsActionPerformed(evt);
            }
        });
        jMenu2.add(showTeamDetails);

        jMenuBar1.add(jMenu2);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/matches.png"))); // NOI18N
        jMenu3.setText("Matches");
        jMenu3.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N

        udpateDeleteMatch.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        udpateDeleteMatch.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        udpateDeleteMatch.setText("Add/Update/Delete Match");
        udpateDeleteMatch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                udpateDeleteMatchActionPerformed(evt);
            }
        });
        jMenu3.add(udpateDeleteMatch);
        jMenu3.add(jSeparator9);

        showMatches.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        showMatches.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        showMatches.setText("All Match Details");
        showMatches.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showMatchesActionPerformed(evt);
            }
        });
        jMenu3.add(showMatches);

        jMenuBar1.add(jMenu3);

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/scores.png"))); // NOI18N
        jMenu4.setText("Score");
        jMenu4.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N

        udpateDeleteScore.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        udpateDeleteScore.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        udpateDeleteScore.setText("Add/Update/Delete Score");
        udpateDeleteScore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                udpateDeleteScoreActionPerformed(evt);
            }
        });
        jMenu4.add(udpateDeleteScore);
        jMenu4.add(jSeparator12);

        showScores.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        showScores.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        showScores.setText("All Score Details");
        showScores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showScoresActionPerformed(evt);
            }
        });
        jMenu4.add(showScores);

        jMenuBar1.add(jMenu4);

        jMenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/stadium.png"))); // NOI18N
        jMenu5.setText("Stadium");
        jMenu5.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N

        updateDeleteStadium.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        updateDeleteStadium.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        updateDeleteStadium.setText("Add/Update/Delete Stadium");
        updateDeleteStadium.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateDeleteStadiumActionPerformed(evt);
            }
        });
        jMenu5.add(updateDeleteStadium);
        jMenu5.add(jSeparator15);

        showStadiums.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        showStadiums.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        showStadiums.setText("All Stadium Details");
        showStadiums.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showStadiumsActionPerformed(evt);
            }
        });
        jMenu5.add(showStadiums);

        jMenuBar1.add(jMenu5);

        jMenu6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/exit.png"))); // NOI18N
        jMenu6.setText("Exit");
        jMenu6.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N

        Logout.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        Logout.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Logout.setText("Logout");
        Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutActionPerformed(evt);
            }
        });
        jMenu6.add(Logout);
        jMenu6.add(jSeparator16);

        exitApplication.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        exitApplication.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        exitApplication.setText("Exit Application");
        exitApplication.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitApplicationActionPerformed(evt);
            }
        });
        jMenu6.add(exitApplication);
        jMenu6.add(jSeparator2);

        AboutUs.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        AboutUs.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        AboutUs.setText("About Us");
        AboutUs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AboutUsActionPerformed(evt);
            }
        });
        jMenu6.add(AboutUs);

        jMenuBar1.add(jMenu6);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void udpateDeleteScoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_udpateDeleteScoreActionPerformed
	new AddUpdateDeleteScore().setVisible(true);
    }//GEN-LAST:event_udpateDeleteScoreActionPerformed

    private void LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutActionPerformed
	int a = JOptionPane.showConfirmDialog(null, "Do you want to Logout", "Select", JOptionPane.YES_NO_OPTION);
	if (a == 0) {
	    setVisible(false);
	    new Login().setVisible(true);
	}
    }//GEN-LAST:event_LogoutActionPerformed

    private void exitApplicationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitApplicationActionPerformed
	int a = JOptionPane.showConfirmDialog(null, "Do you want to Close Application", "Select", JOptionPane.YES_NO_OPTION);
	if (a == 0) {
	    System.exit(0);
	}
    }//GEN-LAST:event_exitApplicationActionPerformed

    private void newPlayerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newPlayerActionPerformed
	new AddUpdateDeletePlayer().setVisible(true);
    }//GEN-LAST:event_newPlayerActionPerformed

    private void showPlayersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showPlayersActionPerformed
	new ShowPlayerDetails().setVisible(true);
    }//GEN-LAST:event_showPlayersActionPerformed

    private void addUpdateDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addUpdateDeleteActionPerformed
	new AddUpdateDeleteTeam().setVisible(true);
    }//GEN-LAST:event_addUpdateDeleteActionPerformed

    private void showTeamDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showTeamDetailsActionPerformed
	new ShowTeamDetails().setVisible(true);
    }//GEN-LAST:event_showTeamDetailsActionPerformed

    private void showMatchesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showMatchesActionPerformed
	new ShowMatchDetails().setVisible(true);
    }//GEN-LAST:event_showMatchesActionPerformed

    private void udpateDeleteMatchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_udpateDeleteMatchActionPerformed
	new AddUpdateDeleteMatch().setVisible(true);
    }//GEN-LAST:event_udpateDeleteMatchActionPerformed

    private void updateDeleteStadiumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateDeleteStadiumActionPerformed
	new AddUpdateDeleteStadium().setVisible(true);
    }//GEN-LAST:event_updateDeleteStadiumActionPerformed

    private void showScoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showScoresActionPerformed
        new ShowScoreDetails().setVisible(true);
    }//GEN-LAST:event_showScoresActionPerformed

    private void showStadiumsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showStadiumsActionPerformed
        new ShowStadiumDetails().setVisible(true);
    }//GEN-LAST:event_showStadiumsActionPerformed

    private void AboutUsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AboutUsActionPerformed
        new AboutUs().setVisible(true);
    }//GEN-LAST:event_AboutUsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
	/* Set the Nimbus look and feel */
	//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
	/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
	 */
	try {
	    for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
		if ("Nimbus".equals(info.getName())) {
		    javax.swing.UIManager.setLookAndFeel(info.getClassName());
		    break;
		}
	    }
	} catch (ClassNotFoundException ex) {
	    java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (InstantiationException ex) {
	    java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (IllegalAccessException ex) {
	    java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (javax.swing.UnsupportedLookAndFeelException ex) {
	    java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	}
	//</editor-fold>

	/* Create and display the form */
	java.awt.EventQueue.invokeLater(new Runnable() {
	    public void run() {
		new Home().setVisible(true);
	    }
	});
    }

    private void setIcon() {
	setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icon.png")));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem AboutUs;
    private javax.swing.JMenuItem Logout;
    private javax.swing.JMenuItem addUpdateDelete;
    private javax.swing.JMenuItem exitApplication;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator12;
    private javax.swing.JPopupMenu.Separator jSeparator15;
    private javax.swing.JPopupMenu.Separator jSeparator16;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator9;
    private javax.swing.JMenuItem newPlayer;
    private javax.swing.JMenuItem showMatches;
    private javax.swing.JMenuItem showPlayers;
    private javax.swing.JMenuItem showScores;
    private javax.swing.JMenuItem showStadiums;
    private javax.swing.JMenuItem showTeamDetails;
    private javax.swing.JMenuItem udpateDeleteMatch;
    private javax.swing.JMenuItem udpateDeleteScore;
    private javax.swing.JMenuItem updateDeleteStadium;
    // End of variables declaration//GEN-END:variables
}
